openapi: 3.0.0
info:
  title: URL Shortener API
  version: 1.0.0
  description: API documentation for a URL shortening service with authentication and user-specific analytics.

servers:
  - url: http://localhost:3000

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User registered successfully

  /api/auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful

  /api/auth/logout:
    post:
      summary: Logout user
      responses:
        '200':
          description: Logout successful

  /api/auth/me:
    get:
      summary: Get current authenticated user
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Current user info

  /api/create:
    post:
      summary: Create short URL (with or without login)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [url]
              properties:
                url:
                  type: string
                  example: https://example.com/very/long/url
                slug:
                  type: string
                  example: custom123
      responses:
        '200':
          description: Short URL created
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrl:
                    type: string

  /api/user/urls:
    post:
      summary: Get all URLs created by the authenticated user
      security:
        - cookieAuth: []
      responses:
        '200':
          description: List of user URLs
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  urls:
                    type: array
                    items:
                      type: object
                      properties:
                        full_url:
                          type: string
                        short_url:
                          type: string
                        createdAt:
                          type: string
                          format: date-time

  /{id}:
    get:
      summary: Redirect to original long URL using short code
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirects to the original URL
        '404':
          description: Short URL not found

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: accessToken
